services:
    acme.latexrenderer.listener:
        class: bigbadaboom\latexrenderer\event\main_listener
        arguments:
            - '@dbal.conn'
            - '@template'
        tags:
            - { name: event.listener }